# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: local390390
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: callit-consumer-lambda
# "service" is the name of this project. This will also be added to your AWS resource names.
service: consumer-lambda

provider:
  name: aws
  runtime: nodejs20.x

functions:
  hello:
    handler: handler.hello
