org: local390390
app: callit-consumer-lambda
service: consumer-lambda

provider:
  name: aws
  runtime: nodejs20.x
  endpoint: http://localhost:4566

custom:
  localstack:
    stages:
      - dev

plugins:
  - serverless-localstack

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
