version: '3.8'

services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    ports:
      - "3000:3000"
  
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
  
  kafka-broker-1:
    image: apache/kafka:latest
    container_name: kafka-broker-1
    ports:
      - "9092:9092"
    networks:
      app-network:
        ipv4_address: 172.25.0.10

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16