global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'minha-aplicacao'
    static_configs:
      - targets: ['localhost:8080']  
    metrics_path: '/metrics'
    scrape_interval: 10s 