org: local390390
app: callit-producer-lambda
service: producer-lambda

provider:
  name: aws
  runtime: nodejs20.x
  endpoint: http://localhost:4566

custom:
  localstack:
    stages:
      - dev

plugins:
  - serverless-localstack

functions:
  hello:
    handler: main.openticket
    events:
      - http:
          method: POST
          path: /open/ticket